import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import Components //
import Navbar from "@/components/molecule/navbar";
import LenisWrapper from "@/components/atom/lenis-wrapper";
import HeaderDesktop from "@/components/molecule/header-desktop";
import Footer from "@/components/molecule/footer";

const aeonikLight = localFont({
	src: "./fonts/aeonik-light.otf",
	weight: "300",
	style: "normal",
	variable: "--font-aeonik-light",
});

const aeonikRegular = localFont({
	src: "./fonts/aeonik-regular.otf",
	weight: "400",
	style: "normal",
	variable: "--font-aeonik-regular",
});

const aeonikMedium = localFont({
	src: "./fonts/aeonik-medium.otf",
	weight: "500",
	style: "normal",
	variable: "--font-aeonik-medium",
});

const satoshi = localFont({
	src: "./fonts/satoshi-regular.otf",
	weight: "300",
	style: "normal",
	variable: "--font-satoshi",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${aeonikLight.variable} ${aeonikRegular.variable} ${aeonikMedium.variable} ${satoshi.variable} bg-bgbase`}
			>
				{/* Mobile header */}
				<header className="flex lg:hidden">
					<Navbar />
				</header>

				{/* Desktop sidebar */}
				<header className="hidden lg:flex">
					<Navbar variant="sidebar" />
				</header>

				{/* Main content area */}
				<main className="lg:ml-[100px] lg:pt-[100px]">
					{/* Fixed header (desktop only) */}
					<div className="hidden lg:flex">
						<HeaderDesktop />
					</div>

					{/* Smooth scrolling wrapper */}
					<LenisWrapper>{children}</LenisWrapper>
				</main>

				{/* Footer aligned with content */}
				<div className="lg:ml-[100px]">
					<Footer />
				</div>
			</body>
		</html>
	);
}
